import type { Program } from "@hull/compiler";
import type { OnProgress, ProgressEvent } from "@hull/studio";

export type { OnProgress, ProgressEvent } from "@hull/studio";

// One environment's stack on the backend in the developer's account.
export type StackTarget = {
  project: string;
  stack: string;
  region: string;
  // The Pulumi backend, s3://<state bucket>?region=<region>; it takes
  // precedence over any Pulumi Cloud login the developer may have.
  backendUrl: string;
  // Unlocks the stack's secrets; generated by Hull on the first deploy.
  passphrase: string;
};

// What a preview would do, by operation: create, update, delete, same...
export type PreviewResult = { changes: Record<string, number> };

// The deploy engine (ADR 0004): what `hull plan`, `hull deploy` and `hull
// destroy` need from Pulumi, small enough to fake in tests. Settled by the
// milestone 1 second spike; preview added for milestone 2.
export type DeployEngine = {
  // Pre-flight: the engine can run at all. Throws a message that says what
  // to install when it cannot.
  check(): Promise<void>;
  // What running the program on the stack would change, without changing
  // it; the events are the ones `up` emits, with the operation planned.
  preview(target: StackTarget, program: Program, onProgress: OnProgress): Promise<PreviewResult>;
  // Runs the inline program on the stack and returns the stack outputs as
  // plain values.
  up(target: StackTarget, program: Program, onProgress: OnProgress): Promise<Record<string, unknown>>;
  destroy(target: StackTarget, onProgress: OnProgress): Promise<void>;
  removeStack(target: StackTarget): Promise<void>;
};

// The developer's account on the provider, as far as deploy needs it before
// the engine runs: who they are and the bucket that holds their state.
export type ProviderAccount = {
  // Throws a message naming the profile and region tried when no
  // credentials resolve.
  identity(region: string): Promise<{ account: string; profile: string }>;
  // Creates the bucket if missing: region location constraint, all public
  // access blocked, versioning on.
  ensureStateBucket(name: string, region: string): Promise<"created" | "existed">;
};

// Unused at runtime; keeps the event type in this module's exports.
export type { ProgressEvent as EngineProgressEvent };
