import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { blueprintFileName, type Blueprint } from "@hull/blueprint";
import { CompileError } from "./errors.js";
import { databaseLinkVariables } from "./link.js";

// The binding module (CONTEXT.md): the generated TypeScript a tier gets for
// every intent it is linked to, one exported object per intent, typed by
// role. A convenience over the link's environment variable contract; the
// contract itself is what a non-TypeScript tier would read.
//
// This module knows nothing of Pulumi so the studio can regenerate the
// bindings on every save without loading the deploy machinery.

// Relative to the directory holding the blueprint. Gitignored by `hull init`.
export const bindingsDirectory = join(".hull", "bindings");

export const generatedHeader = `// Generated by Hull from ${blueprintFileName}. Do not edit: every studio save and every deploy rewrites this file.`;

// File name (relative to the bindings folder) to source.
export type BindingFiles = Record<string, string>;

type DatabaseTarget = { intent: string; linkedFrom: string[] };

// One object per intent any tier is linked to, in blueprint order. In v0 the
// only link is read-write to a relational database, so every binding is a
// database binding; a link to any other kind is refused rather than dropped.
export function generateBindings(blueprint: Blueprint): BindingFiles {
  const targets = new Map<string, DatabaseTarget>();
  for (const [tier, intent] of Object.entries(blueprint.intents)) {
    if (intent.kind !== "http-api") continue;
    for (const link of intent.links ?? []) {
      const kind = blueprint.intents[link.to]?.kind;
      if (kind !== "relational-database") {
        throw new CompileError(`intent "${tier}" links to "${link.to}" of kind ${kind}, which has no binding in this version`);
      }
      const target = targets.get(link.to) ?? { intent: link.to, linkedFrom: [] };
      target.linkedFrom.push(tier);
      targets.set(link.to, target);
    }
  }
  return { "index.ts": indexModule([...targets.values()]) };
}

// Writes the module files under the bindings folder of `directory` and
// returns the paths written.
export function writeBindings(directory: string, blueprint: Blueprint): string[] {
  const folder = join(directory, bindingsDirectory);
  mkdirSync(folder, { recursive: true });
  return Object.entries(generateBindings(blueprint)).map(([name, source]) => {
    const path = join(folder, name);
    writeFileSync(path, source);
    return path;
  });
}

function indexModule(targets: DatabaseTarget[]): string {
  if (targets.length === 0) {
    return `${generatedHeader}\n\n// No tier is linked to an intent; add a link in ${blueprintFileName} and this module gains an export per linked intent.\nexport {};\n`;
  }
  const exports = targets.map(({ intent, linkedFrom }) => {
    const names = databaseLinkVariables(intent);
    return `/** The \`${intent}\` intent, linked read-write from ${linkedFrom.map((tier) => `\`${tier}\``).join(", ")}. */
export const ${intent}: DatabaseBinding = databaseBinding("${intent}", {
  host: "${names.host}",
  port: "${names.port}",
  name: "${names.name}",
  user: "${names.user}",
  passwordArn: "${names.passwordArn}",
});`;
  });
  return `${generatedHeader}

import { GetSecretValueCommand, SecretsManagerClient } from "@aws-sdk/client-secrets-manager";

${exports.join("\n\n")}

${databaseRuntime}`;
}

// The runtime every database binding shares, emitted into the module so the
// bindings folder depends on nothing but the AWS SDK.
const databaseRuntime = `// A read-write link to a relational database.
export type DatabaseBinding = {
  /**
   * A Postgres URL for the linked database. Reads the link's environment
   * variables, fetches the managed master password from Secrets Manager the
   * first time and keeps it for the lifetime of the process, so a Lambda
   * does not fetch it on every request. SSL is required, as RDS Postgres
   * enforces it by default.
   */
  connectionString(): Promise<string>;
};

// The shape of databaseLinkVariables in link.ts, restated here because the
// generated module depends on nothing of Hull's.
type ContractVariables = { host: string; port: string; name: string; user: string; passwordArn: string };

let secretsClient: SecretsManagerClient | undefined;

function databaseBinding(intent: string, variables: ContractVariables): DatabaseBinding {
  let cached: Promise<string> | undefined;

  const read = (variable: string): string => {
    const value = process.env[variable];
    if (!value) {
      throw new Error(
        \`\${variable} is not set; the \${intent} binding only works inside a tier deployed by Hull with a link to \${intent}\`,
      );
    }
    return value;
  };

  const resolve = async (): Promise<string> => {
    const host = read(variables.host);
    const port = read(variables.port);
    const name = read(variables.name);
    const user = read(variables.user);
    const passwordArn = read(variables.passwordArn);
    secretsClient ??= new SecretsManagerClient({});
    const secret = await secretsClient.send(new GetSecretValueCommand({ SecretId: passwordArn }));
    if (!secret.SecretString) throw new Error(\`the secret \${passwordArn} of \${intent} has no string value\`);
    const { password } = JSON.parse(secret.SecretString) as { password?: unknown };
    if (typeof password !== "string") throw new Error(\`the secret \${passwordArn} of \${intent} holds no password\`);
    return \`postgresql://\${encodeURIComponent(user)}:\${encodeURIComponent(password)}@\${host}:\${port}/\${name}?sslmode=require\`;
  };

  return {
    connectionString() {
      // The promise is cached, not the value, so concurrent first calls share
      // one fetch; a failed fetch is dropped so the next call retries.
      cached ??= resolve().catch((error: unknown) => {
        cached = undefined;
        throw error;
      });
      return cached;
    },
  };
}
`;
