import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { blueprintFileName, isTier, type Blueprint } from "@hull/blueprint";
import { CompileError } from "./errors.js";
import { databaseLinkVariables, queueLinkVariables } from "./link.js";

// The binding module (CONTEXT.md): the generated TypeScript a tier gets for
// every intent it is linked to, one exported object per intent, typed by
// role. A convenience over the link's environment variable contract; the
// contract itself is what a non-TypeScript tier would read.
//
// This module knows nothing of Pulumi so the studio can regenerate the
// bindings on every save without loading the deploy machinery.

// Relative to the directory holding the blueprint. Gitignored by `hull init`.
export const bindingsDirectory = join(".hull", "bindings");

export const generatedHeader = `// Generated by Hull from ${blueprintFileName}. Do not edit: every studio save and every deploy rewrites this file.`;

// File name (relative to the bindings folder) to source.
export type BindingFiles = Record<string, string>;

type Target =
  | { kind: "relational-database"; intent: string; linkedFrom: string[] }
  | { kind: "queue"; intent: string; linkedFrom: string[]; roles: Set<string> };

// One object per intent any tier is linked to, in blueprint order. A link to
// a database gives a database binding; a link to a queue gives a queue
// binding with the methods of the roles linked to it; a link to any other
// kind is refused rather than dropped.
export function generateBindings(blueprint: Blueprint): BindingFiles {
  const targets = new Map<string, Target>();
  for (const [tier, intent] of Object.entries(blueprint.intents)) {
    if (!isTier(intent)) continue;
    for (const link of intent.links ?? []) {
      const kind = blueprint.intents[link.to]?.kind;
      if (kind !== "relational-database" && kind !== "queue") {
        throw new CompileError(`intent "${tier}" links to "${link.to}" of kind ${kind}, which has no binding in this version`);
      }
      let target = targets.get(link.to);
      if (!target) {
        target = kind === "queue" ? { kind, intent: link.to, linkedFrom: [], roles: new Set() } : { kind, intent: link.to, linkedFrom: [] };
        targets.set(link.to, target);
      }
      target.linkedFrom.push(tier);
      if (target.kind === "queue") target.roles.add(link.role);
    }
  }
  return { "index.ts": indexModule([...targets.values()]) };
}

// Writes the module files under the bindings folder of `directory` and
// returns the paths written.
export function writeBindings(directory: string, blueprint: Blueprint): string[] {
  const folder = join(directory, bindingsDirectory);
  mkdirSync(folder, { recursive: true });
  return Object.entries(generateBindings(blueprint)).map(([name, source]) => {
    const path = join(folder, name);
    writeFileSync(path, source);
    return path;
  });
}

const tierList = (tiers: string[]) => tiers.map((tier) => `\`${tier}\``).join(", ");

// The methods a queue binding exposes, in the order of the roles.
const queueMethods: Record<string, string> = { produce: "send", consume: "consume" };

function indexModule(targets: Target[]): string {
  if (targets.length === 0) {
    return `${generatedHeader}\n\n// No tier is linked to an intent; add a link in ${blueprintFileName} and this module gains an export per linked intent.\nexport {};\n`;
  }
  const databases = targets.filter((target) => target.kind === "relational-database");
  const queues = targets.filter((target) => target.kind === "queue");
  const exports = targets.map((target) => {
    if (target.kind === "relational-database") {
      const names = databaseLinkVariables(target.intent);
      return `/** The \`${target.intent}\` intent, linked read-write from ${tierList(target.linkedFrom)}. */
export const ${target.intent}: DatabaseBinding = databaseBinding("${target.intent}", {
  host: "${names.host}",
  port: "${names.port}",
  name: "${names.name}",
  user: "${names.user}",
  passwordArn: "${names.passwordArn}",
});`;
    }
    const names = queueLinkVariables(target.intent);
    const methods = Object.entries(queueMethods)
      .filter(([role]) => target.roles.has(role))
      .map(([, method]) => `"${method}"`);
    return `/** The \`${target.intent}\` intent, linked from ${tierList(target.linkedFrom)} (${[...target.roles].join(", ")}). */
export const ${target.intent}: Pick<QueueBinding, ${methods.join(" | ")}> = queueBinding("${target.intent}", { url: "${names.url}", arn: "${names.arn}" });`;
  });
  const imports = [
    ...(databases.length > 0 ? ['import { GetSecretValueCommand, SecretsManagerClient } from "@aws-sdk/client-secrets-manager";'] : []),
    ...(queues.length > 0 ? ['import { SQSClient, SendMessageCommand } from "@aws-sdk/client-sqs";'] : []),
  ];
  const runtimes = [readVariableRuntime, ...(databases.length > 0 ? [databaseRuntime] : []), ...(queues.length > 0 ? [queueRuntime] : [])];
  return `${generatedHeader}

${imports.join("\n")}

${exports.join("\n\n")}

${runtimes.join("\n")}`;
}

// The runtime every binding shares, emitted into the module so the bindings
// folder depends on nothing but the AWS SDK.
const readVariableRuntime = `// A contract variable of a link, present only inside a tier deployed by Hull.
function readVariable(intent: string, variable: string): string {
  const value = process.env[variable];
  if (!value) {
    throw new Error(\`\${variable} is not set; the \${intent} binding only works inside a tier deployed by Hull with a link to \${intent}\`);
  }
  return value;
}
`;

const databaseRuntime = `// A read-write link to a relational database.
export type DatabaseBinding = {
  /**
   * A Postgres URL for the linked database. Reads the link's environment
   * variables, fetches the managed master password from Secrets Manager the
   * first time and keeps it for the lifetime of the process, so a Lambda
   * does not fetch it on every request. SSL is required, as RDS Postgres
   * enforces it by default.
   */
  connectionString(): Promise<string>;
};

// The shape of databaseLinkVariables in link.ts, restated here because the
// generated module depends on nothing of Hull's.
type DatabaseVariables = { host: string; port: string; name: string; user: string; passwordArn: string };

let secretsClient: SecretsManagerClient | undefined;

function databaseBinding(intent: string, variables: DatabaseVariables): DatabaseBinding {
  let cached: Promise<string> | undefined;

  const resolve = async (): Promise<string> => {
    const host = readVariable(intent, variables.host);
    const port = readVariable(intent, variables.port);
    const name = readVariable(intent, variables.name);
    const user = readVariable(intent, variables.user);
    const passwordArn = readVariable(intent, variables.passwordArn);
    secretsClient ??= new SecretsManagerClient({});
    const secret = await secretsClient.send(new GetSecretValueCommand({ SecretId: passwordArn }));
    if (!secret.SecretString) throw new Error(\`the secret \${passwordArn} of \${intent} has no string value\`);
    const { password } = JSON.parse(secret.SecretString) as { password?: unknown };
    if (typeof password !== "string") throw new Error(\`the secret \${passwordArn} of \${intent} holds no password\`);
    return \`postgresql://\${encodeURIComponent(user)}:\${encodeURIComponent(password)}@\${host}:\${port}/\${name}?sslmode=require\`;
  };

  return {
    connectionString() {
      // The promise is cached, not the value, so concurrent first calls share
      // one fetch; a failed fetch is dropped so the next call retries.
      cached ??= resolve().catch((error: unknown) => {
        cached = undefined;
        throw error;
      });
      return cached;
    },
  };
}
`;

const queueRuntime = `// The SQS batch a consuming Lambda receives, and what it answers: the ids
// of the messages that failed, so only those are redelivered.
export type SqsEvent = { Records: { messageId: string; body: string }[] };
export type SqsBatchResponse = { batchItemFailures: { itemIdentifier: string }[] };
export type SqsHandler = (event: SqsEvent) => Promise<SqsBatchResponse>;

// A link to a queue: send for a produce link, consume for a consume link.
export type QueueBinding = {
  /** JSON-encodes the message and sends it to the linked queue. */
  send(message: unknown): Promise<void>;
  /**
   * A Lambda handler for the queue's batches: decodes each message body as
   * JSON and calls the handler once per message; the messages whose handler
   * threw, or whose body was not JSON, are reported as batch item failures.
   */
  consume<Message>(handler: (message: Message) => Promise<void>): SqsHandler;
};

// The shape of queueLinkVariables in link.ts, restated here because the
// generated module depends on nothing of Hull's.
type QueueVariables = { url: string; arn: string };

let sqsClient: SQSClient | undefined;

function queueBinding(intent: string, variables: QueueVariables): QueueBinding {
  return {
    async send(message) {
      const url = readVariable(intent, variables.url);
      sqsClient ??= new SQSClient({});
      await sqsClient.send(new SendMessageCommand({ QueueUrl: url, MessageBody: JSON.stringify(message) }));
    },
    consume(handler) {
      return async (event) => {
        const batchItemFailures: { itemIdentifier: string }[] = [];
        for (const record of event.Records) {
          try {
            await handler(JSON.parse(record.body) as Parameters<typeof handler>[0]);
          } catch {
            batchItemFailures.push({ itemIdentifier: record.messageId });
          }
        }
        return { batchItemFailures };
      };
    },
  };
}
`;
